export const AUTH_LIBRARIAN_ADMIN_LOGIN = 'AUTH_LIBRARIAN_ADMIN_LOGIN'
export const LIBRARIAN_ADMIN_SHOW = 'LIBRARIAN_ADMIN_SHOW'
export const AUTH_LIBRARIAN_ADMIN_ERROR = 'AUTH_LIBRARIAN_ADMIN_ERROR'
export const AUTH_MAIN_ADMIN_LOGIN = 'AUTH_MAIN_ADMIN_LOGIN'
export const MAIN_ADMIN_SHOW = 'MAIN_ADMIN_SHOW'
export const AUTH_MAIN_ADMIN_ERROR = 'AUTH_MAIN_ADMIN_ERROR'

