const AUTH_LIBRARIAN_ADMIN_LOGIN = 'AUTH_LIBRARIAN_ADMIN_LOGIN'
const LIBRARIAN_ADMIN_SHOW = 'LIBRARIAN_ADMIN_SHOW'
const AUTH_LIBRARIAN_ADMIN_ERROR = 'AUTH_LIBRARIAN_ADMIN_ERROR'
const AUTH_MAIN_ADMIN_LOGIN = 'AUTH_MAIN_ADMIN_LOGIN'
const MAIN_ADMIN_SHOW = 'MAIN_ADMIN_SHOW'
const AUTH_MAIN_ADMIN_ERROR = 'AUTH_MAIN_ADMIN_ERROR'

